///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class AccountModelUserTokenData {
/*
{
  "access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2VkdW1hc3Rlci5tYWJkZWxzYW1pZS5vbmxpbmUvYXBpL2F1dGgvc3R1ZGVudC9sb2dpbiIsImlhdCI6MTcwMTYyMjc1MSwiZXhwIjoxNzAxNjI2MzUxLCJuYmYiOjE3MDE2MjI3NTEsImp0aSI6InZvd2xJZk1DaU1YdG5kNlMiLCJzdWIiOiIxIiwicHJ2IjoiOWM0MjllNmE2MGNkNTI4NTQ3M2YyYzhiYzcwMWVjMDk0OGRmNGQ4YyJ9.rxR3MnDd38iAzmD6_Tyuc_JW3MLmlvfuhlEhn77AvtI",
  "token_type": "bearer",
  "expires_in": 0
}
*/

  String? accessToken;
  String? tokenType;
  int? expiresIn;

  AccountModelUserTokenData({
    this.accessToken,
    this.tokenType,
    this.expiresIn,
  });
  AccountModelUserTokenData.fromJson(Map<String, dynamic> json) {
    accessToken = json['access_token']?.toString();
    tokenType = json['token_type']?.toString();
    expiresIn = json['expires_in']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['access_token'] = accessToken;
    data['token_type'] = tokenType;
    data['expires_in'] = expiresIn;
    return data;
  }
}

class AccountModelUser {
/*
{
  "id": 1,
  "first_name": "Omar",
  "last_name": "Abdo",
  "email": "omar@gmail.com",
  "gender": "male",
  "image": null,
  "code": "sfsfger1",
  "token_data": {
    "access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2VkdW1hc3Rlci5tYWJkZWxzYW1pZS5vbmxpbmUvYXBpL2F1dGgvc3R1ZGVudC9sb2dpbiIsImlhdCI6MTcwMTYyMjc1MSwiZXhwIjoxNzAxNjI2MzUxLCJuYmYiOjE3MDE2MjI3NTEsImp0aSI6InZvd2xJZk1DaU1YdG5kNlMiLCJzdWIiOiIxIiwicHJ2IjoiOWM0MjllNmE2MGNkNTI4NTQ3M2YyYzhiYzcwMWVjMDk0OGRmNGQ4YyJ9.rxR3MnDd38iAzmD6_Tyuc_JW3MLmlvfuhlEhn77AvtI",
    "token_type": "bearer",
    "expires_in": 0
  },
  "is_enrolled": false,
  "courses": [
    null
  ]
}
*/

  int? id;
  String? firstName;
  String? lastName;
  String? email;
  String? gender;
  String? image;
  String? code;
  AccountModelUserTokenData? tokenData;
  bool? isEnrolled;
  // List<AccountModelUserCourses?>? courses;

  AccountModelUser({
    this.id,
    this.firstName,
    this.lastName,
    this.email,
    this.gender,
    this.image,
    this.code,
    this.tokenData,
    this.isEnrolled,
    // this.courses,
  });
  AccountModelUser.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    firstName = json['first_name']?.toString();
    lastName = json['last_name']?.toString();
    email = json['email']?.toString();
    gender = json['gender']?.toString();
    image = json['image']?.toString();
    code = json['code']?.toString();
    tokenData = (json['token_data'] != null) ? AccountModelUserTokenData.fromJson(json['token_data']) : null;
    isEnrolled = json['is_enrolled'];
    // >>>>>>error<<<<<<
    }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['first_name'] = firstName;
    data['last_name'] = lastName;
    data['email'] = email;
    data['gender'] = gender;
    data['image'] = image;
    data['code'] = code;
    if (tokenData != null) {
      data['token_data'] = tokenData!.toJson();
    }
    data['is_enrolled'] = isEnrolled;
    // >>>>>>error<<<<<<
    return data;
  }
}

class AccountModel {
/*
{
  "status": 200,
  "errorNum": "S000",
  "message": "Logged Successfully",
  "user": {
    "id": 1,
    "first_name": "Omar",
    "last_name": "Abdo",
    "email": "omar@gmail.com",
    "gender": "male",
    "image": null,
    "code": "sfsfger1",
    "token_data": {
      "access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2VkdW1hc3Rlci5tYWJkZWxzYW1pZS5vbmxpbmUvYXBpL2F1dGgvc3R1ZGVudC9sb2dpbiIsImlhdCI6MTcwMTYyMjc1MSwiZXhwIjoxNzAxNjI2MzUxLCJuYmYiOjE3MDE2MjI3NTEsImp0aSI6InZvd2xJZk1DaU1YdG5kNlMiLCJzdWIiOiIxIiwicHJ2IjoiOWM0MjllNmE2MGNkNTI4NTQ3M2YyYzhiYzcwMWVjMDk0OGRmNGQ4YyJ9.rxR3MnDd38iAzmD6_Tyuc_JW3MLmlvfuhlEhn77AvtI",
      "token_type": "bearer",
      "expires_in": 0
    },
    "is_enrolled": false,
    "courses": [
      null
    ]
  }
}
*/

  int? status;
  String? errorNum;
  String? message;
  AccountModelUser? user;

  AccountModel({
    this.status,
    this.errorNum,
    this.message,
    this.user,
  });
  AccountModel.fromJson(Map<String, dynamic> json) {
    status = json['status']?.toInt();
    errorNum = json['errorNum']?.toString();
    message = json['message']?.toString();
    user = (json['user'] != null) ? AccountModelUser.fromJson(json['user']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['errorNum'] = errorNum;
    data['message'] = message;
    if (user != null) {
      data['user'] = user!.toJson();
    }
    return data;
  }
}
