///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CourseDashboardModelCourseUnitsContainersLesson {
/*
{
  "id": 1,
  "title": "الدرس الاول",
  "video": "https://www.youtube.com/watch?v=runIG2kMGbo",
  "video_duration": "15:20:30",
  "content": "المحتوي"
}
*/

  int? id;
  String? title;
  String? video;
  String? videoDuration;
  String? content;

  CourseDashboardModelCourseUnitsContainersLesson({
    this.id,
    this.title,
    this.video,
    this.videoDuration,
    this.content,
  });
  CourseDashboardModelCourseUnitsContainersLesson.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    title = json['title']?.toString();
    video = json['video']?.toString();
    videoDuration = json['video_duration']?.toString();
    content = json['content']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['title'] = title;
    data['video'] = video;
    data['video_duration'] = videoDuration;
    data['content'] = content;
    return data;
  }
}

class CourseDashboardModelCourseUnitsContainers {
/*
{
  "id": 58,
  "type": "lesson",
  "order": 1,
  "quiz_id": null,
  "lesson_id": 1,
  "unit_id": 4,
  "lesson": {
    "id": 1,
    "title": "الدرس الاول",
    "video": "https://www.youtube.com/watch?v=runIG2kMGbo",
    "video_duration": "15:20:30",
    "content": "المحتوي"
  }
}
*/

  int? id;
  String? type;
  int? order;
  String? quizId;
  int? lessonId;
  int? unitId;
  CourseDashboardModelCourseUnitsContainersLesson? lesson;

  CourseDashboardModelCourseUnitsContainers({
    this.id,
    this.type,
    this.order,
    this.quizId,
    this.lessonId,
    this.unitId,
    this.lesson,
  });
  CourseDashboardModelCourseUnitsContainers.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    type = json['type']?.toString();
    order = json['order']?.toInt();
    quizId = json['quiz_id']?.toString();
    lessonId = json['lesson_id']?.toInt();
    unitId = json['unit_id']?.toInt();
    lesson = (json['lesson'] != null) ? CourseDashboardModelCourseUnitsContainersLesson.fromJson(json['lesson']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['type'] = type;
    data['order'] = order;
    data['quiz_id'] = quizId;
    data['lesson_id'] = lessonId;
    data['unit_id'] = unitId;
    if (lesson != null) {
      data['lesson'] = lesson!.toJson();
    }
    return data;
  }
}

class CourseDashboardModelCourseUnits {
/*
{
  "id": 4,
  "title": "الوحده الاولي",
  "order": 1,
  "containers": [
    {
      "id": 58,
      "type": "lesson",
      "order": 1,
      "quiz_id": null,
      "lesson_id": 1,
      "unit_id": 4,
      "lesson": {
        "id": 1,
        "title": "الدرس الاول",
        "video": "https://www.youtube.com/watch?v=runIG2kMGbo",
        "video_duration": "15:20:30",
        "content": "المحتوي"
      }
    }
  ],
  "duration": null
}
*/

  int? id;
  String? title;
  int? order;
  List<CourseDashboardModelCourseUnitsContainers?>? containers;
  String? duration;

  CourseDashboardModelCourseUnits({
    this.id,
    this.title,
    this.order,
    this.containers,
    this.duration,
  });
  CourseDashboardModelCourseUnits.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    title = json['title']?.toString();
    order = json['order']?.toInt();
    if (json['containers'] != null) {
      final v = json['containers'];
      final arr0 = <CourseDashboardModelCourseUnitsContainers>[];
      v.forEach((v) {
        arr0.add(CourseDashboardModelCourseUnitsContainers.fromJson(v));
      });
      containers = arr0;
    }
    duration = json['duration']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['title'] = title;
    data['order'] = order;
    if (containers != null) {
      final v = containers;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['containers'] = arr0;
    }
    data['duration'] = duration;
    return data;
  }
}

class CourseDashboardModelCourse {
/*
{
  "id": 3,
  "title": "مادة الفيزياء",
  "desc": "مادة الفزياء  وصف ",
  "annual_price": 600,
  "tags": [
    "الفيزياء"
  ],
  "image": "assets/images/rows/1703019265400781943_2066108287074686_7341597626417228928_n.jpg",
  "thumbnail": "assets/images/thumbnails/1703019265file.jpg",
  "level_id": 2,
  "units": [
    {
      "id": 4,
      "title": "الوحده الاولي",
      "order": 1,
      "containers": [
        {
          "id": 58,
          "type": "lesson",
          "order": 1,
          "quiz_id": null,
          "lesson_id": 1,
          "unit_id": 4,
          "lesson": {
            "id": 1,
            "title": "الدرس الاول",
            "video": "https://www.youtube.com/watch?v=runIG2kMGbo",
            "video_duration": "15:20:30",
            "content": "المحتوي"
          }
        }
      ],
      "duration": null
    }
  ],
  "level_title": "الصف الثاني الاعدادي"
}
*/

  int? id;
  String? title;
  String? desc;
  int? annualPrice;
  List<String?>? tags;
  String? image;
  String? thumbnail;
  int? levelId;
  List<CourseDashboardModelCourseUnits?>? units;
  String? levelTitle;

  CourseDashboardModelCourse({
    this.id,
    this.title,
    this.desc,
    this.annualPrice,
    this.tags,
    this.image,
    this.thumbnail,
    this.levelId,
    this.units,
    this.levelTitle,
  });
  CourseDashboardModelCourse.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    title = json['title']?.toString();
    desc = json['desc']?.toString();
    annualPrice = json['annual_price']?.toInt();
    if (json['tags'] != null) {
      final v = json['tags'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      tags = arr0;
    }
    image = json['image']?.toString();
    thumbnail = json['thumbnail']?.toString();
    levelId = json['level_id']?.toInt();
    if (json['units'] != null) {
      final v = json['units'];
      final arr0 = <CourseDashboardModelCourseUnits>[];
      v.forEach((v) {
        arr0.add(CourseDashboardModelCourseUnits.fromJson(v));
      });
      units = arr0;
    }
    levelTitle = json['level_title']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['title'] = title;
    data['desc'] = desc;
    data['annual_price'] = annualPrice;
    if (tags != null) {
      final v = tags;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v);
      }
      data['tags'] = arr0;
    }
    data['image'] = image;
    data['thumbnail'] = thumbnail;
    data['level_id'] = levelId;
    if (units != null) {
      final v = units;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['units'] = arr0;
    }
    data['level_title'] = levelTitle;
    return data;
  }
}

class CourseDashboardModel {
/*
{
  "status": 200,
  "errorNum": "S000",
  "message": "Course has been returned successfully",
  "course": {
    "id": 3,
    "title": "مادة الفيزياء",
    "desc": "مادة الفزياء  وصف ",
    "annual_price": 600,
    "tags": [
      "الفيزياء"
    ],
    "image": "assets/images/rows/1703019265400781943_2066108287074686_7341597626417228928_n.jpg",
    "thumbnail": "assets/images/thumbnails/1703019265file.jpg",
    "level_id": 2,
    "units": [
      {
        "id": 4,
        "title": "الوحده الاولي",
        "order": 1,
        "containers": [
          {
            "id": 58,
            "type": "lesson",
            "order": 1,
            "quiz_id": null,
            "lesson_id": 1,
            "unit_id": 4,
            "lesson": {
              "id": 1,
              "title": "الدرس الاول",
              "video": "https://www.youtube.com/watch?v=runIG2kMGbo",
              "video_duration": "15:20:30",
              "content": "المحتوي"
            }
          }
        ],
        "duration": null
      }
    ],
    "level_title": "الصف الثاني الاعدادي"
  }
}
*/

  int? status;
  String? errorNum;
  String? message;
  CourseDashboardModelCourse? course;

  CourseDashboardModel({
    this.status,
    this.errorNum,
    this.message,
    this.course,
  });
  CourseDashboardModel.fromJson(Map<String, dynamic> json) {
    status = json['status']?.toInt();
    errorNum = json['errorNum']?.toString();
    message = json['message']?.toString();
    course = (json['course'] != null) ? CourseDashboardModelCourse.fromJson(json['course']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['errorNum'] = errorNum;
    data['message'] = message;
    if (course != null) {
      data['course'] = course!.toJson();
    }
    return data;
  }
}
