///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ParentRegisterModelUserStudentsPivot {
/*
{
  "parent_id": 34,
  "student_id": 1
}
*/

  int? parentId;
  int? studentId;

  ParentRegisterModelUserStudentsPivot({
    this.parentId,
    this.studentId,
  });
  ParentRegisterModelUserStudentsPivot.fromJson(Map<String, dynamic> json) {
    parentId = json['parent_id']?.toInt();
    studentId = json['student_id']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['parent_id'] = parentId;
    data['student_id'] = studentId;
    return data;
  }
}

class ParentRegisterModelUserStudents {
/*
{
  "id": 1,
  "first_name": "Omar",
  "last_name": "Abdo",
  "email": "omar@gmail.com",
  "phone": "01146127749",
  "gender": "male",
  "code": "sfsfger1",
  "image": null,
  "level_id": null,
  "created_at": "2023-12-10T20:20:27.000000Z",
  "updated_at": "2023-12-10T20:20:27.000000Z",
  "pivot": {
    "parent_id": 34,
    "student_id": 1
  }
}
*/

  int? id;
  String? firstName;
  String? lastName;
  String? email;
  String? phone;
  String? gender;
  String? code;
  String? image;
  String? levelId;
  String? createdAt;
  String? updatedAt;
  ParentRegisterModelUserStudentsPivot? pivot;

  ParentRegisterModelUserStudents({
    this.id,
    this.firstName,
    this.lastName,
    this.email,
    this.phone,
    this.gender,
    this.code,
    this.image,
    this.levelId,
    this.createdAt,
    this.updatedAt,
    this.pivot,
  });
  ParentRegisterModelUserStudents.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    firstName = json['first_name']?.toString();
    lastName = json['last_name']?.toString();
    email = json['email']?.toString();
    phone = json['phone']?.toString();
    gender = json['gender']?.toString();
    code = json['code']?.toString();
    image = json['image']?.toString();
    levelId = json['level_id']?.toString();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    pivot = (json['pivot'] != null) ? ParentRegisterModelUserStudentsPivot.fromJson(json['pivot']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['first_name'] = firstName;
    data['last_name'] = lastName;
    data['email'] = email;
    data['phone'] = phone;
    data['gender'] = gender;
    data['code'] = code;
    data['image'] = image;
    data['level_id'] = levelId;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    if (pivot != null) {
      data['pivot'] = pivot!.toJson();
    }
    return data;
  }
}

class ParentRegisterModelUserTokenData {
/*
{
  "access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2VkdW1hc3Rlci5tYWJkZWxzYW1pZS5vbmxpbmUvYXBpL2F1dGgvcGFyZW50L3JlZ2lzdGVyIiwiaWF0IjoxNzAyMjQxOTI2LCJleHAiOjE3MDIyNDU1MjYsIm5iZiI6MTcwMjI0MTkyNiwianRpIjoiRGxMSGtqaXExckJxMGlmMiIsInN1YiI6IjM0IiwicHJ2IjoiZDg5YjNiNDg2M2I5MTBmNzgzYTlhZGQ4NWU1ODAzYzU1YzVjZTc2MyJ9.VoFz5hdBMRu2df3mXjImIWTNn39fZQkITsWu27Wz_Pg",
  "token_type": "bearer",
  "expires_in": 0
}
*/

  String? accessToken;
  String? tokenType;
  int? expiresIn;

  ParentRegisterModelUserTokenData({
    this.accessToken,
    this.tokenType,
    this.expiresIn,
  });
  ParentRegisterModelUserTokenData.fromJson(Map<String, dynamic> json) {
    accessToken = json['access_token']?.toString();
    tokenType = json['token_type']?.toString();
    expiresIn = json['expires_in']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['access_token'] = accessToken;
    data['token_type'] = tokenType;
    data['expires_in'] = expiresIn;
    return data;
  }
}

class ParentRegisterModelUser {
/*
{
  "first_name": "sdf",
  "last_name": "sdf",
  "email": "hsksfs@test.com",
  "gender": "male",
  "phone": "01146127749",
  "updated_at": "2023-12-10T20:58:46.000000Z",
  "created_at": "2023-12-10T20:58:46.000000Z",
  "id": 34,
  "token_data": {
    "access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2VkdW1hc3Rlci5tYWJkZWxzYW1pZS5vbmxpbmUvYXBpL2F1dGgvcGFyZW50L3JlZ2lzdGVyIiwiaWF0IjoxNzAyMjQxOTI2LCJleHAiOjE3MDIyNDU1MjYsIm5iZiI6MTcwMjI0MTkyNiwianRpIjoiRGxMSGtqaXExckJxMGlmMiIsInN1YiI6IjM0IiwicHJ2IjoiZDg5YjNiNDg2M2I5MTBmNzgzYTlhZGQ4NWU1ODAzYzU1YzVjZTc2MyJ9.VoFz5hdBMRu2df3mXjImIWTNn39fZQkITsWu27Wz_Pg",
    "token_type": "bearer",
    "expires_in": 0
  },
  "students": [
    {
      "id": 1,
      "first_name": "Omar",
      "last_name": "Abdo",
      "email": "omar@gmail.com",
      "phone": "01146127749",
      "gender": "male",
      "code": "sfsfger1",
      "image": null,
      "level_id": null,
      "created_at": "2023-12-10T20:20:27.000000Z",
      "updated_at": "2023-12-10T20:20:27.000000Z",
      "pivot": {
        "parent_id": 34,
        "student_id": 1
      }
    }
  ]
}
*/

  String? firstName;
  String? lastName;
  String? email;
  String? gender;
  String? phone;
  String? updatedAt;
  String? createdAt;
  int? id;
  ParentRegisterModelUserTokenData? tokenData;
  List<ParentRegisterModelUserStudents?>? students;

  ParentRegisterModelUser({
    this.firstName,
    this.lastName,
    this.email,
    this.gender,
    this.phone,
    this.updatedAt,
    this.createdAt,
    this.id,
    this.tokenData,
    this.students,
  });
  ParentRegisterModelUser.fromJson(Map<String, dynamic> json) {
    firstName = json['first_name']?.toString();
    lastName = json['last_name']?.toString();
    email = json['email']?.toString();
    gender = json['gender']?.toString();
    phone = json['phone']?.toString();
    updatedAt = json['updated_at']?.toString();
    createdAt = json['created_at']?.toString();
    id = json['id']?.toInt();
    tokenData = (json['token_data'] != null) ? ParentRegisterModelUserTokenData.fromJson(json['token_data']) : null;
    if (json['students'] != null) {
      final v = json['students'];
      final arr0 = <ParentRegisterModelUserStudents>[];
      v.forEach((v) {
        arr0.add(ParentRegisterModelUserStudents.fromJson(v));
      });
      students = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['first_name'] = firstName;
    data['last_name'] = lastName;
    data['email'] = email;
    data['gender'] = gender;
    data['phone'] = phone;
    data['updated_at'] = updatedAt;
    data['created_at'] = createdAt;
    data['id'] = id;
    if (tokenData != null) {
      data['token_data'] = tokenData!.toJson();
    }
    if (students != null) {
      final v = students;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['students'] = arr0;
    }
    return data;
  }
}

class ParentRegisterModel {
/*
{
  "status": 200,
  "errorNum": "S000",
  "message": "Registered Successfully",
  "user": {
    "first_name": "sdf",
    "last_name": "sdf",
    "email": "hsksfs@test.com",
    "gender": "male",
    "phone": "01146127749",
    "updated_at": "2023-12-10T20:58:46.000000Z",
    "created_at": "2023-12-10T20:58:46.000000Z",
    "id": 34,
    "token_data": {
      "access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2VkdW1hc3Rlci5tYWJkZWxzYW1pZS5vbmxpbmUvYXBpL2F1dGgvcGFyZW50L3JlZ2lzdGVyIiwiaWF0IjoxNzAyMjQxOTI2LCJleHAiOjE3MDIyNDU1MjYsIm5iZiI6MTcwMjI0MTkyNiwianRpIjoiRGxMSGtqaXExckJxMGlmMiIsInN1YiI6IjM0IiwicHJ2IjoiZDg5YjNiNDg2M2I5MTBmNzgzYTlhZGQ4NWU1ODAzYzU1YzVjZTc2MyJ9.VoFz5hdBMRu2df3mXjImIWTNn39fZQkITsWu27Wz_Pg",
      "token_type": "bearer",
      "expires_in": 0
    },
    "students": [
      {
        "id": 1,
        "first_name": "Omar",
        "last_name": "Abdo",
        "email": "omar@gmail.com",
        "phone": "01146127749",
        "gender": "male",
        "code": "sfsfger1",
        "image": null,
        "level_id": null,
        "created_at": "2023-12-10T20:20:27.000000Z",
        "updated_at": "2023-12-10T20:20:27.000000Z",
        "pivot": {
          "parent_id": 34,
          "student_id": 1
        }
      }
    ]
  }
}
*/

  int? status;
  String? errorNum;
  String? message;
  ParentRegisterModelUser? user;

  ParentRegisterModel({
    this.status,
    this.errorNum,
    this.message,
    this.user,
  });
  ParentRegisterModel.fromJson(Map<String, dynamic> json) {
    status = json['status']?.toInt();
    errorNum = json['errorNum']?.toString();
    message = json['message']?.toString();
    user = (json['user'] != null) ? ParentRegisterModelUser.fromJson(json['user']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['errorNum'] = errorNum;
    data['message'] = message;
    if (user != null) {
      data['user'] = user!.toJson();
    }
    return data;
  }
}
