///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class StudentRegisterModelUserLevel {
/*
{
  "id": 2,
  "title": "الصف الثاني الاعدادي",
  "order": 2,
  "image": "assets/images/banners/level2.jpg"
}
*/

  int? id;
  String? title;
  int? order;
  String? image;

  StudentRegisterModelUserLevel({
    this.id,
    this.title,
    this.order,
    this.image,
  });
  StudentRegisterModelUserLevel.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    title = json['title']?.toString();
    order = json['order']?.toInt();
    image = json['image']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['title'] = title;
    data['order'] = order;
    data['image'] = image;
    return data;
  }
}

class StudentRegisterModelUserTokenData {
/*
{
  "access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2VkdW1hc3Rlci5tYWJkZWxzYW1pZS5vbmxpbmUvYXBpL2F1dGgvc3R1ZGVudC9yZWdpc3RlciIsImlhdCI6MTcwMzEwNjg5OCwiZXhwIjoxNzAzMTEwNDk4LCJuYmYiOjE3MDMxMDY4OTgsImp0aSI6IlJuclUxS1NNcGJ2ZzA0NUoiLCJzdWIiOiIzMyIsInBydiI6IjljNDI5ZTZhNjBjZDUyODU0NzNmMmM4YmM3MDFlYzA5NDhkZjRkOGMifQ.sGE_Ni-cFLMtsafF50uv6vVA8AP8k2NFfg23SQ-ZbUU",
  "token_type": "bearer",
  "expires_in": 0
}
*/

  String? accessToken;
  String? tokenType;
  int? expiresIn;

  StudentRegisterModelUserTokenData({
    this.accessToken,
    this.tokenType,
    this.expiresIn,
  });
  StudentRegisterModelUserTokenData.fromJson(Map<String, dynamic> json) {
    accessToken = json['access_token']?.toString();
    tokenType = json['token_type']?.toString();
    expiresIn = json['expires_in']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['access_token'] = accessToken;
    data['token_type'] = tokenType;
    data['expires_in'] = expiresIn;
    return data;
  }
}

class StudentRegisterModelUser {
/*
{
  "first_name": "sdf",
  "last_name": "sdf",
  "email": "sd1f1@gmail.com",
  "gender": "male",
  "phone": "01146127749",
  "level_id": "2",
  "code": "GhUc58",
  "id": 33,
  "token_data": {
    "access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2VkdW1hc3Rlci5tYWJkZWxzYW1pZS5vbmxpbmUvYXBpL2F1dGgvc3R1ZGVudC9yZWdpc3RlciIsImlhdCI6MTcwMzEwNjg5OCwiZXhwIjoxNzAzMTEwNDk4LCJuYmYiOjE3MDMxMDY4OTgsImp0aSI6IlJuclUxS1NNcGJ2ZzA0NUoiLCJzdWIiOiIzMyIsInBydiI6IjljNDI5ZTZhNjBjZDUyODU0NzNmMmM4YmM3MDFlYzA5NDhkZjRkOGMifQ.sGE_Ni-cFLMtsafF50uv6vVA8AP8k2NFfg23SQ-ZbUU",
    "token_type": "bearer",
    "expires_in": 0
  },
  "level": {
    "id": 2,
    "title": "الصف الثاني الاعدادي",
    "order": 2,
    "image": "assets/images/banners/level2.jpg"
  }
}
*/

  String? firstName;
  String? lastName;
  String? email;
  String? gender;
  String? phone;
  String? levelId;
  String? code;
  int? id;
  StudentRegisterModelUserTokenData? tokenData;
  StudentRegisterModelUserLevel? level;

  StudentRegisterModelUser({
    this.firstName,
    this.lastName,
    this.email,
    this.gender,
    this.phone,
    this.levelId,
    this.code,
    this.id,
    this.tokenData,
    this.level,
  });
  StudentRegisterModelUser.fromJson(Map<String, dynamic> json) {
    firstName = json['first_name']?.toString();
    lastName = json['last_name']?.toString();
    email = json['email']?.toString();
    gender = json['gender']?.toString();
    phone = json['phone']?.toString();
    levelId = json['level_id']?.toString();
    code = json['code']?.toString();
    id = json['id']?.toInt();
    tokenData = (json['token_data'] != null) ? StudentRegisterModelUserTokenData.fromJson(json['token_data']) : null;
    level = (json['level'] != null) ? StudentRegisterModelUserLevel.fromJson(json['level']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['first_name'] = firstName;
    data['last_name'] = lastName;
    data['email'] = email;
    data['gender'] = gender;
    data['phone'] = phone;
    data['level_id'] = levelId;
    data['code'] = code;
    data['id'] = id;
    if (tokenData != null) {
      data['token_data'] = tokenData!.toJson();
    }
    if (level != null) {
      data['level'] = level!.toJson();
    }
    return data;
  }
}

class StudentRegisterModel {
/*
{
  "status": 200,
  "errorNum": "S000",
  "message": "Registered Successfully",
  "user": {
    "first_name": "sdf",
    "last_name": "sdf",
    "email": "sd1f1@gmail.com",
    "gender": "male",
    "phone": "01146127749",
    "level_id": "2",
    "code": "GhUc58",
    "id": 33,
    "token_data": {
      "access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2VkdW1hc3Rlci5tYWJkZWxzYW1pZS5vbmxpbmUvYXBpL2F1dGgvc3R1ZGVudC9yZWdpc3RlciIsImlhdCI6MTcwMzEwNjg5OCwiZXhwIjoxNzAzMTEwNDk4LCJuYmYiOjE3MDMxMDY4OTgsImp0aSI6IlJuclUxS1NNcGJ2ZzA0NUoiLCJzdWIiOiIzMyIsInBydiI6IjljNDI5ZTZhNjBjZDUyODU0NzNmMmM4YmM3MDFlYzA5NDhkZjRkOGMifQ.sGE_Ni-cFLMtsafF50uv6vVA8AP8k2NFfg23SQ-ZbUU",
      "token_type": "bearer",
      "expires_in": 0
    },
    "level": {
      "id": 2,
      "title": "الصف الثاني الاعدادي",
      "order": 2,
      "image": "assets/images/banners/level2.jpg"
    }
  }
}
*/

  int? status;
  String? errorNum;
  String? message;
  StudentRegisterModelUser? user;

  StudentRegisterModel({
    this.status,
    this.errorNum,
    this.message,
    this.user,
  });
  StudentRegisterModel.fromJson(Map<String, dynamic> json) {
    status = json['status']?.toInt();
    errorNum = json['errorNum']?.toString();
    message = json['message']?.toString();
    user = (json['user'] != null) ? StudentRegisterModelUser.fromJson(json['user']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['errorNum'] = errorNum;
    data['message'] = message;
    if (user != null) {
      data['user'] = user!.toJson();
    }
    return data;
  }
}
